name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: CodeQL and Dependabot Report Action
      uses: rsdmike/github-security-report-action@v3.0.4
      with:
        token: ${{ secrets.SECURITY_TOKEN }}
        sarifReportDir: ./result/example.js.sarif
        node-version: 20
            
